matrix:

  include:

    - compiler: gcc
    
      os:
           - linux
      sudo: required
      dist: trusty
      language: cpp
    
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
            - libpcap-dev

      env: COMPILER=g++-5

      script:
            - mkdir build
            - cd build
            - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc
            - make
            - make test

    - compiler: clang
    
      os:
           - linux
      sudo: required
      dist: trusty
      language: cpp    
    
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-all-dev
            - libpcap-dev

      env: COMPILER=clang++-3.7
      
      script:
            - mkdir build
            - cd build
            - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc
            - make
            - make test
