language: cpp

compiler:
- gcc
#- clang

os:
- linux

before_script:
- sudo apt-get install -qq libboost-all-dev libpcap-dev

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc
- make
- make test
