os:
- linux

sudo: required
dist: trusty
language: cpp

matrix:
  include:

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
            - libpcap-dev
      env: COMPILER=g++-5

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-all-dev
            - libpcap-dev

      env: COMPILER=clang++-3.7

# TEST RUN SCRIPT
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc
- make
- make test
